convertFuncList=[
"convert_format_user_number" ,
"sh_convert_switch_wlan_roam_filename" ,
"convert_conbineDateTime" ,
"convert_filter_wireless_service" ,
"convert_format_opp_number" ,
"convert_format_opp_number" ,
"convert_gsm_cfcalltype_adjust" ,
"convert_gsm_duration" ,
"convert_gsm_format_anumber" ,
"convert_gsm_format_anumber" ,
"convert_gsm_format_anumber" ,
"convert_huawei_call_type" ,
"convert_huawei_msoftx_gsm_cfcalltype_by_servicecode" ,
"convert_huawei_user_number_exchange" ,
"convert_judge_0_duration" ,
"convert_judge_imsi_empty" ,
"convert_judge_longest_duration" ,
"convert_set_ori_basic_charge_1008X" ,
"public_convert_gsm_inboss_cdr_60" ,
"convert_filter_gsm_someservice_from_msc" ,
"convert_split_record_local_by_user_number_gx" ,
"guangxi_convert_gsm_split_merge_by_sequenceno" ,
"convert_gprs_partial_type_ericsson" ,
"convert_format_opp_number" ,
"neimeng_convert_gsm_vpmn_cdr",
"neimeng_convert_gsm_duration",
"neimeng_convert_filter_gsm_someservice_from_msc",
"guangxi_convert_gsm_sequenceno_ericsson",
"neimeng_convert_huawei_trunk_id",
"zj_convert_set_mscid_according_filename_validTime",
"convert_filter_roam_jtw",
"convert_ims_check_audio_video",
"convert_ims_sequenceno_huawei",
"convert_switch_user_opp_by_calltype",
"zj_convert_ilr_add_basicfee",
"neimeng_vcard_scp_scpid",

###########get from gsm prefix
"convert_ericsson_vpmn_judge_new"                 ,
"convert_set_moc_id_null_when_vhe"                ,
"convert_gsm_bill_indicate"                       ,
"public_convert_gsm_inboss_cdr_60"                ,
"convert_filter_drtype_pdppgsm"                   ,
"convert_gsm_sequenceno_ericsson"                 ,
"convert_gsm_ericsson_otherparty"                 ,
"public_convert_Qcharge_by_servicetype"           ,
"convert_gsm_opp_number"                          ,
"convert_gsm_siemens_otherparty"                  ,
"convert_siemens_gsm_SupplementaryService"        ,
"zj_convert_huawei_filter_service"                ,
"public_convert_cut_off_0_from_a_number_01008X"   ,
"convert_filter_national_sms"                     ,
"convert_siemens_cell_lac"                        ,
"convert_vhe_by_vpmn_judge_ericsson"              ,
"zj_convert_set_mscid_according_filename"         ,
"public_convert_opp_number_159786_del"            ,
"convert_format_opp_number"                       ,
"public_convert_splite_pbx"                       ,
"public_convert_cut_off_0_from_opp_number_01008X" ,
"convert_siemens_set_otherparty"                  ,
"convert_gsm_split_merge_by_sequenceno"           ,
"convert_huawei_user_number_exchange"             ,
"convert_i_gsm_call_type"                         ,
"convert_ericsson_vpmn_judge"                     ,
"public_convert_gsm_vpmn_60"                      ,
"convert_ericsson_cfcalltype"                     ,
"convert_change_ericssion_oppnumber"              ,
"convert_siemens_gsm_vpmn"                        ,
"zj_convert_judge_user_equal_opp"                 ,
"convert_huawei_gsm_start_time"                   ,
"convert_set_moc_id_null_when_vhe_ericsson"       ,
"convert_vhe_by_vpmn_judge"                       ,
"convert_gsm_sequenceno_huawei"                   ,
"convert_cell_lac"                                ,

###from xz template
"convert_filter_gsm_vpmn_cdr",
"public_convert_check_if_all_digital",
"convert_alcatel_gsm_otherparty",
"convert_alcatel_gsmv7_vpmn",
"convert_ipnew_opptype_modify",
"convert_alcatel_call_type",
"convert_alcatel_gsm_anumber",
"convert_ims_hw_calltype",
"convert_alcatel_a5020_sas_servicecode",
"convert_alcatel_gsmv7_SupplementaryService",
"convert_alcatel_service_code",
"convert_tag_msc_inboss_cdr",
"convert_msrn",
"convert_filter_starttime_abnormal",
"convert_b_gsm_call_type",
"convert_siemens_service_code",
"zj_convert_supplement_imsi_15",
"zj_convert_format_user_number_gateway",
"xizang_convert_filter_gsm_cnr",
"zj_convert_siemens_call_type",
"zj_convert_siemens_user_number",
"zj_convert_siemens_smot_opp_number", 
"zj_convert_siemens_filter_service",  
"xizang_convert_judge_longest_duration", 
"xizang_convert_huawei_cs_gsm_vpmn",      
"xizang_convert_gsm_sequenceno_huawei",   
"xizang_convert_split_cwt",               
"convert_gsm_split_cwt_lmerge_by_sequenceno",
"zj_convert_alcatel_gsm_user_number_gateway",
"zj_convert_alcatel_filter_service",    
"xizang_convert_siemens_gateway_cfw",   
"convert_huawei_gsm_otherparty",       
"xizang_convert_judge_fillcard_id",     
"xizang_convert_vc_to_user_number",    
"xizang_convert_servicetype_infotype",   
"xizang_convert_filter_1700_186",              
"zj_convert_judge_shortest_duartion",       
"xizang_convert_splite_smof_sms",             
"xizang_convert_ussd_insert_ori_toll_charge",  
"xizang_convert_check_hywg_usernumber",         
"xizang_convert_ismg_hywg",                 
"zj_convert_switch_wlan_roam_filename",        

]