tempList=[
#"ip_card.dcd                 ", 
#"ericsson_gsm.dcd            ",
#"huawei_cs.dcd               ",
#"huawei_gsm_252.dcd          ",
#"huawei_gsm_252_gw.dcd       ",
#"vpmn_vpn_cdr.dcd            ",
#"vpmn_gsm.dcd                ",
#"ed_gsm.dcd                  ",
#"eq_gsm.dcd                  ",
#"d_gsm.dcd                   ",
#"gsm_400.dcd                 ",
#"i_gsm.dcd                   ",
#"q_gsm.dcd                   ",
#"mvp.dcd                     ",
#"ims_as.dcd                  ",
#"uploader_d_gsm.dcd          ",
#"r_gsm.dcd                   ",
#"sd_gsm.dcd                  ",
#"d_vpmn_scp.dcd              ",
#"rd_gsm.dcd                  ",
#"hu_roam.dcd                 ",
#"hd_roam.dcd                 ",
#"vcard_vc_pps.dcd            ",
#"vcard_scp.dcd               ",
#"vc_sett.dcd                 ",
#"huawei_sms.dcd              ",
#"sms_inter.dcd               ",
#"ismg_smg.dcd                ",
#"ismg_smg_telecom.dcd        ",
#"sms_iot.dcd                 ",
#"sms_vpmn.dcd                ",
#"sms_zte.dcd                 ",
#"ismg_cm_down.dcd            ",
#"voice_magazine.dcd          ",
#"ussd.dcd                    ",
#"ussd_local_base.dcd         ",
#"ussd_local_busi.dcd         ",
#"ismg_ismg.dcd               ",
#"sms_regard_inter.dcd        ",
#"pim_down.dcd                ",
#"cring.dcd                   ",
#"magic_voice.dcd             ",
#"ismg_ym_down.dcd            ",
#"ismg_yx_down.dcd            ",
#"mobile_map.dcd              ",
#"video_cring_down.dcd        ",
#"ismg_caiyun.dcd             ",
#"ismg_pm_down.dcd            ",
#"ismg_m_down.dcd             ",
#"ismg_ci_down.dcd            ",
#"ismg_hywg.dcd               ",
#"ismg_qyyx.dcd               ",
#"bboss_mrdread.dcd           ",
#"sms_bboss.dcd               ",
#"pgm_smsmms.dcd              ",
#"mth_iot.dcd                 ",
#"wireless_card.dcd           ",
#"wireless_card_cring.dcd     ",
#"magic_voice_ch.dcd          ",
#"ismg_12580_down.dcd         ",
#"wap.dcd                     ",
#"mobile_cartoon.dcd          ",
#"mrd.dcd                     ",
#"mrddb.dcd                   ",
#"mobile_flash.dcd            ",
#"pda.dcd                     ",
#"wap_local.dcd               ",
#"widget.dcd                  ",
#"ippay_pip.dcd               ",
#"ippay_gip.dcd               ",
#"ippay_bip.dcd               ",
#"mms.dcd                     ",
#"mms_inter.dcd               ",
#"mms_union.dcd               ",
#"mms_ori.dcd                 ",
#"mms_ci_down.dcd             ",
#"mms_bboss.dcd               ",
#"mms_hywg.dcd                ",
#"wlan.dcd                    ",
#"wlan_iwlan.dcd              ",
#"wlan_wt.dcd                 ",
#"wlan_wli.dcd                ",
#"wlan_kjh.dcd                ",
#"gp_down.dcd                 ",
#"mp.dcd                      ",
#"mobile_navigation_gd.dcd    ",
#"mobile_market.dcd           ",
#"dkxf_down.dcd               ",
#"poc.dcd                     ",
#"multi_voice.dcd             ",
#"addvalue_meeting.dcd        ",
#"cas.dcd                     ",
#"ctd.dcd                     ",
#"efp.dcd                     ",
#"stream_down.dcd             ",
#"ip_ggprs.dcd                ",
#"ip_ggprs_w.dcd              ",
#"ericsson_LTE_ps.dcd         ",
#"huawei_ps.dcd               ",
#"huawei_LTE_ps.dcd           ",
#"gprs_cngd_down.dcd          ",
#"gprs_cngd_down_lte.dcd      ",
#"gprs_tap3.dcd               ",
#"gprs_tap3_lte.dcd           ",
#"ggprs_iot_cngo.dcd          ",
#"ggprs_iot_cngd.dcd          ",
#"gmrd.dcd                    ",
#"gprs_g3nb.dcd               ",
#"idc_ips.dcd                 ",
#"ericsson_ps.dcd             ",
#"ericsson_ps.dcd             ",
#"huawei_ps.dcd               ",
#"huawei_ps.dcd               ",
#"huawei_LTE_ps.dcd           ",
#"ericsson_LTE_ps.dcd         ",
#"gg_gprs.dcd                 ",
#"g_gprs.dcd                  ",
#"ggprs_group_bill.dcd        ",
#"ggprs_group_bill_local.dcd  ",

"ip_card.dcd",
"ed_gsm.dcd",
"ericsson_gsm.dcd",
"eq_gsm.dcd",
"huawei_cs.dcd",
"huawei_gsm_252.dcd",
"d_gsm.dcd",
"uploader_d_gsm.dcd",
"i_gsm.dcd",
"mvp.dcd",
"q_gsm.dcd",
"voice_magazine.dcd",
"r_gsm.dcd",
"sd_gsm.dcd",
"ims_as.dcd",
"gsm_400.dcd",
"vcard_scp.dcd",
"vc_sett.dcd",
"vcard_vc_pps.dcd",
"vpmn_gsm.dcd",
"d_vpmn_scp.dcd",
"vpmn_vpn_cdr.dcd",
"sms_inter.dcd",
"huawei_sms.dcd",
"ismg_smg_telecom.dcd",
"sms_zte.dcd",
"sms_vpmn.dcd",
"sms_iot.dcd",
"ismg_smg.dcd",
"sms_regard_inter.dcd",
"ismg_cm_down.dcd",
"ismg_ci_down.dcd",
"ismg_ym_down.dcd",
"ismg_pm_down.dcd",
"ismg_hywg.dcd",
"ismg_ismg.dcd",
"ismg_yx_down.dcd",
"ussd.dcd",
"mobile_map.dcd",
"video_cring_down.dcd",
"pim_down.dcd",
"sms_bboss.dcd",
"wireless_card.dcd",
"ismg_12580_down.dcd",
"ismg_caiyun.dcd",
"ussd_local_base.dcd",
"ussd_local_busi.dcd",
"magic_voice.dcd",
"cring.dcd",
"ismg_m_down.dcd",
"ismg_qyyx.dcd",
"bboss_mrdread.dcd",
"pgm_smsmms.dcd",
"wireless_card_cring.dcd",
"magic_voice_ch.dcd",
"mth_iot.dcd",
"wap.dcd",
"wap_local.dcd",
"mobile_flash.dcd",
"mrd.dcd",
"mrddb.dcd",
"pda.dcd",
"widget.dcd",
"mobile_cartoon.dcd",
"ippay_bip.dcd",
"ippay_pip.dcd",
"ippay_gip.dcd",
"mms.dcd",
"mms_inter.dcd",
"mms_bboss.dcd",
"mms_union.dcd",
"mms_ori.dcd",
"mms_hywg.dcd",
"mms_ci_down.dcd",
"wlan.dcd",
"wlan_wt.dcd",
"wlan_wli.dcd",
"wlan_kjh.dcd",
"wlan_iwlan.dcd",
"mobile_market.dcd",
"mobile_navigation_gd.dcd",
"gp_down.dcd",
"dkxf_down.dcd",
"mp.dcd",
"rd_gsm.dcd",
"addvalue_meeting.dcd",
"efp.dcd",
"cas.dcd",
"ctd.dcd",
"poc.dcd",
"stream_down.dcd",
"gprs_cngd_down.dcd",
"gprs_cngd_down_lte.dcd",
"huawei_LTE_ps.dcd",
"huawei_ps.dcd",
"gprs_tap3.dcd",
"gprs_tap3_lte.dcd",
"gprs_g3nb.dcd",
"gmrd.dcd",
"ericsson_LTE_ps.dcd",
"gg_gprs.dcd",
"idc_ips.dcd",
"ggprs_iot_cngd.dcd",
"hu_roam.dcd",
"ip_ggprs.dcd",
"ip_ggprs_w.dcd",
"ericsson_ps.dcd",
"g_gprs.dcd",
"ggprs_group_bill.dcd",
"hd_roam.dcd",
"ggprs_group_bill_local.dcd",
"ggprs_iot_cngo.dcd",
"multi_voice.dcd",
]

specProcessTempList=[
"ggprs_iot_cngd.dcd", 
"ggprs_iot_cngo.dcd",
"gprs_g3nb.dcd",
"gmrd.dcd",
"huawei_ps_ggsn.dcd",
"gprs_tap3.dcd",
"gprs_cngd_down.dcd",
"gprs_tap3_lte.dcd",
"gprs_cngd_down_lte.dcd",
"huawei_LTE_pgw.dcd",
"ericsson_LTE_pgw.dcd", 
]

voiceTempList=[
"ericsson_gsm.dcd",
"huawei_gsm_252.dcd",
"ericsson_gsm.dcd",
"huawei_gsm_252.dcd",
"huawei_gsm_252_gw.dcd",
"d_gsm.dcd",
"q_gsm.dcd",
"i_gsm.dcd",
"r_gsm.dcd",
"rd_gsm.dcd",
"multi_voice.dcd",
"huawei_cs.dcd",
"ims_as.dcd",
"gsm_400.dcd",
"ericsson_gsm.dcd",
"ed_gsm.dcd",
"eq_gsm.dcd",
"sd_gsm.dcd",
"ip_card.dcd",
"ippay_pip.dcd",
"ippay_gip.dcd",
"ippay_bip.dcd",
"vcard_vc_pps.dcd",
"vc_sett.dcd",
"vcard_scp.dcd",
"magic_voice_ch.dcd",
"ip_ggprs_w.dcd",
"ericsson_gsm_ng.dcd",
];