#! /usr/bin/python
# -*- coding: utf-8 -*-

#前置网元相关
xdr_field_list = [                                                       
"Sxdr.common.SERVICE_ID                                      ",
"Sxdr.common.DR_TYPE                                         ",
"Sxdr.common.IMSI                                            ",
"Sxdr.common.USER_NUMBER                                     ",
"Sxdr.common.STOP_TIME                                       ",
"Sxdr.common.VPLMN1                                          ",
"Sxdr.common.VPLMN2                                          ",
"Sxdr.common.VPLMN3                                          ",
"Sxdr.total_xdr.SUB_COMMON.NOTIFY_TYPE                       ",
"Sxdr.total_xdr.SUB_COMMON.START_TIME                        ",
"Sxdr.total_xdr.SUB_COMMON.DURATION                          ",
"Sxdr.common.MNS_TYPE                                        ",
"Sxdr.common.IMEI                                            ",
"Sxdr.common.SEQUENCE_ID                                     ",
"Sxdr.total_xdr.SUB_COMMON.LAC_ID                            ",
"Sxdr.total_xdr.SUB_COMMON.CELL_ID                           ",
"Sxdr.common.STOP_CAUSE                                      ",
"Sxdr.common.ORIGINAL_FILE                                   ",
"Sxdr.total_xdr.SUB_COMMON.SERVICE_TYPE                      ",
"Sxdr.total_xdr.SUB_COMMON.SERVICE_CODE                      ",
"Sxdr.common.ORI_CHARGE                                      ",
"Sxdr.total_xdr.SUB_COMMON.RECORD_TYPE                       ",
"Sxdr.common.GPRS_SPEC_INFO.CALLER_INDICATE                  ",
"Sxdr.common.GPRS_SPEC_INFO.SGSN_ADDRESS                     ",
"Sxdr.common.GPRS_SPEC_INFO.TRIGGER_TYPE                     ",
"Sxdr.common.GPRS_SPEC_INFO.MSNC                             ",
"Sxdr.common.GPRS_SPEC_INFO.RAC                              ",
"Sxdr.common.GPRS_SPEC_INFO.CHARGING_ID                      ",
"Sxdr.common.GPRS_SPEC_INFO.GGSN_ADDRESS                     ",
"Sxdr.common.GPRS_SPEC_INFO.APN_NI                           ",
"Sxdr.common.GPRS_SPEC_INFO.APN_OI                           ",
"Sxdr.common.GPRS_SPEC_INFO.SYSTEM_TYPE                      ",
"Sxdr.common.GPRS_SPEC_INFO.PDP_TYPE                         ",
"Sxdr.common.GPRS_SPEC_INFO.PDP_ADDRESS                      ",
"Sxdr.common.GPRS_SPEC_INFO.CAUSE_CLOSE                      ",
"Sxdr.common.GPRS_SPEC_INFO.COMBINE_RESULT                   ",
"Sxdr.common.GPRS_SPEC_INFO.CHARGING_CHARACTERISTICS         ",
"Sxdr.common.GPRS_SPEC_INFO.CC_SELECTION_MODE                ",
"Sxdr.common.GPRS_SPEC_INFO.SGSN_PLMN                        ",
"Sxdr.common.GPRS_SPEC_INFO.PARTIAL_TYPE_INDICATOR           ",
"Sxdr.common.GPRS_INFO.DEAL_DATETIME                         ",
"Sxdr.common.GPRS_SPEC_INFO.REC_SEQ_NO                       ",
"Sxdr.common.GPRS_SPEC_INFO.LOCAL_REC_SEQ_NO                 ",
"Sxdr.common.GPRS_SPEC_INFO.GGSN_ID                          ",
"Sxdr.common.GPRS_SPEC_INFO.SGSN_ID                          ",
"Sxdr.total_xdr.SUB_COMMON.BILL_FLAG                         ",
"Sxdr.common.GPRS_SPEC_INFO.SERVICE_USAGE                    ",
"Sxdr.total_xdr.SUB_COMMON.UP_VOLUME                         ",
"Sxdr.total_xdr.SUB_COMMON.DOWN_VOLUME                       ",
"Sxdr.common.GPRS_SPEC_INFO.PARTIAL_NUM                      ",
"Sxdr.common.GPRS_SPEC_INFO.TARIFF_QCS_LIST                  ",
"Sxdr.common.GPRS_SPEC_INFO.GPRS_WLAN_INFO.HOSTSPOT_ID       ",
"Sxdr.common.GPRS_SPEC_INFO.GPRS_WLAN_INFO.AC_ADDRESS        ",
"Sxdr.common.GPRS_SPEC_INFO.GPRS_WLAN_INFO.AS_ADDRESS        ",
"Sxdr.common.GPRS_SPEC_INFO.GPRS_WLAN_INFO.HOME_CARRIER      ",
"Sxdr.common.GPRS_SPEC_INFO.GPRS_WLAN_INFO.ROAM_CARRIER      ",
"Sxdr.total_xdr.SUB_COMMON.SP_CODE                           ",
"Sxdr.total_xdr.SUB_COMMON.CDR_QUERY_FLAG                    ",
"Sxdr.total_xdr.SUB_COMMON.PRODUCT_ID                        ",
"Sxdr.total_xdr.SUB_COMMON.ROAM_TYPE                         ",
"Sxdr.total_xdr.SUB_COMMON.USER_BASE_INFO.HPLMN1             ",
"Sxdr.total_xdr.SUB_COMMON.USER_BASE_INFO.HPLMN2             ",
"Sxdr.total_xdr.SUB_COMMON.USER_BASE_INFO.HPLMN3             ",
"Sxdr.total_xdr.SUB_COMMON.RATING_FLAG                       ",
"Sxdr.total_xdr.SUB_COMMON.CONDITION_ID                      ",
"Sxdr.total_xdr.SUB_COMMON.OCS_MONITOR_CDR                   ",
"Sxdr.total_xdr.SUB_COMMON.BACKUP_DATE                       ",
"Sxdr.total_xdr.SUB_COMMON.RESERVE1                          ",
"Sxdr.total_xdr.SUB_COMMON.RESERVE2                          ",
"Sxdr.total_xdr.SUB_COMMON.RESERVE3                          ",
"Sxdr.total_xdr.SUB_COMMON.RESERVE4                          ",
"Sxdr.common.OTHER_INFO1                                     ",
"Sxdr.common.OTHER_INFO2                                     ",
"Sxdr.common.OTHER_INFO3                                     ",
"Sxdr.common.OTHER_INFO4                                     ",
"Sxdr.total_xdr.SUB_COMMON.USER_PROPERTY                     ",



]